version: "3"
services:
  acopiosf-consultas-backend:
    image: https://github.com/patedwins/pruebaPichincha/pichincha-transaccion
    container_name: pichincha-transaccion
    labels:
      - app=acopiosf-cartera
      - env=backend
    restart: always
    env_file:
      - ./.env
    ports:
      - "4040:8081"
    networks:
      - app-services
networks:
  app-services:
    external: false
